name: Building CEFLIB

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies

      - name: Install Python requirements
        run: |
          pip install -r codebase/PYTHON/requirements.txt
          python -c "import site; print(site.getsitepackages()[0])"
      
      - name: Build core C library
        run: |
          cd codebase/LIB
          ../build clean raz all
          cd ../C
          ../build clean raz all

      - name: Build Python library
        run: |
          cd codebase/PYTHON
          ../build clean raz all
          ls -la ./builds

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ceflib-python-libs
          path: codebase/PYTHON/builds/*.so
